name: Appdome build-2secure
description: Appdome Build-2secure in GitHub
branding:
  icon: 'bluetooth'
  color: 'blue'

inputs:
  APPDOME_API_TOKEN:
    description: 'Appdome API key'
    default: 'None'
    required: true
  APP_FILE:
    description: 'APK file'
    default: 'None'
    required: true
  FUSION_SET_ID:
    description: "Appdome FusionSetId iOS/Android"
    default: 'None'
    required: true
  SIGN_OPTIONS:
    type: choice
    description: "iOS/Android Signin option"
    options: 
    - SIGN_ON_APPDOME
    - PRIVATE_SIGNING
    - AUTO_DEV_SIGNING
    required: true
  KEYSTORE_FILE:
    description: 'Keystore sign file'
    default: 'None'
    required: false
  MOBILE_PROVISION_PROFILE_FILE:
    description: 'iOS sign file'
    default: 'None'
    required: false
  ENTITLEMENTS_FILE:
    description: 'iOS sign file'
    default: 'None'
    required: false
  KEYSTORE_PASSWORD:
    description: 'Keystore password sign file'
    default: 'None'
    required: false
  KEYSTORE_ALIAS:
    description: 'keystore alias'
    default: 'None'
    required: false
  KEYSTORE_KEY_PASSWORD:
    description: 'keystore key password'
    default: 'None'
    required: false
  SIGN_FINGERPRINT:
    description: 'signing sha1 fingerprint'
    default: 'None'
    required: false
  GOOGLE-PLAY-SIGNING:
    description: 'Google Play App Signing program'
    type: boolean
    default: "false"
    required: false
  GOOGLE_PLAY_SIGNING:
    description: 'Google Play App Signing program'
    type: boolean
    default: "false"
    required: false
  CERTIFICATE_FILE:
    description: 'Certificate sign file'
    default: 'None'
    required: false
  CERTIFICATE_PASSWORD:
    description: 'Certificate password sign file'
    default: 'None'
    required: false
  TEAM-ID:
    description: 'your team-id'
    default: 'None'
    required: false
  TEAM_ID:
    description: 'your team-id'
    default: 'None'
    required: false
  BUILD_WITH_LOGS:
    description: 'whether build with logs or not'
    default: false
    type: boolean
    required: false
  SECOND_OUTPUT:
    description: 'Should there be a second universal apk output (for aab apps)?'
    default: false
    type: boolean
    required: false
  OUTPUT_APP_NAME:
    description: 'Specify a name for the output app (without the extension)'
    default: "None"
    required: false
  BUILD_TO_TEST:
    type: choice
    description: "Build to test option"
    options:
      - bitbar
      - browserstack
      - lambdatest
      - saucelabs
    required: false
    default: "None"
runs:
  using: "composite"
  steps:
    - name: Convention fix
      id: convention-fix
      run: |
        if [ -n "${{ inputs.GOOGLE_PLAY_SIGNING }}" ]; then
          GOOGLE_PLAY_SIGNING="${{ inputs.GOOGLE-PLAY-SIGNING }}"
        else
          GOOGLE_PLAY_SIGNING="${{ inputs.GOOGLE_PLAY_SIGNING }}"
        fi

        if [ "${{ inputs.TEAM_ID }}" == "None" ]; then
          TEAM_ID="${{ inputs.TEAM-ID }}"
        else
          TEAM_ID="${{ inputs.TEAM_ID }}"
        fi

        echo "TEAM_ID=${TEAM_ID}" >> $GITHUB_OUTPUT
        echo "GOOGLE_PLAY_SIGNING=${GOOGLE_PLAY_SIGNING}" >> $GITHUB_OUTPUT
      shell: bash
    - name: Cloning appdome-api-python github repository
      uses: actions/checkout@master
      with:
        repository: Appdome/appdome-api-python
        ref: refs/heads/main
        path: appdome
    - name: Install requirements
      run: sudo pip3 install -r appdome/requirements.txt
      shell: bash
    - name: Cloning actions
      uses: actions/checkout@master
      with:
        repository: Appdome/github_build-2secure
        ref: refs/heads/main
        path: actions
    - name: permissions
      run: chmod +x ./actions/actions/appdome_build_sign.py | chmod +x ./actions/actions/files_manager.py
      shell: bash
    - name: Run download action files
      run: python3 ./actions/actions/files_manager.py -a "${{ inputs.APP_FILE }}" -k "${{ inputs.KEYSTORE_FILE }}" -c "${{ inputs.CERTIFICATE_FILE }}" -pp "${{ inputs.MOBILE_PROVISION_PROFILE_FILE }}" -e "${{ inputs.ENTITLEMENTS_FILE }}"
      shell: bash
    - name: Run appdome bash action files
      run: python3 ./actions/actions/appdome_build_sign.py -sign ${{ inputs.SIGN_OPTIONS }} -api_key ${{ inputs.APPDOME_API_TOKEN }} -fs ${{ inputs.FUSION_SET_ID }} -cp ${{ inputs.CERTIFICATE_PASSWORD }} -kp ${{ inputs.KEYSTORE_PASSWORD }} -ka ${{ inputs.KEYSTORE_ALIAS }} -kkp ${{ inputs.KEYSTORE_KEY_PASSWORD }} -team_id ${{ steps.convention-fix.outputs.TEAM_ID }} -google-play-signing ${{ steps.convention-fix.outputs.GOOGLE_PLAY_SIGNING }} -signing_fingerprint ${{ inputs.SIGN_FINGERPRINT }} -bl ${{ inputs.BUILD_WITH_LOGS }} --sign_second_output ${{inputs.SECOND_OUTPUT}} -bt ${{inputs.BUILD_TO_TEST}} -o ${{inputs.OUTPUT_APP_NAME}}
      shell: bash
    - name: Determine OUTPUT_APP_NAME directory
      id: get-output-dir
      run: |
        OUTPUT_APP_NAME="${{ inputs.OUTPUT_APP_NAME }}"
        if [ -z "$OUTPUT_APP_NAME" ] || [ "$OUTPUT_APP_NAME" == "None" ]; then # Default values
          OUTPUT_PATH="./output/"
          OUTPUT_APP_NAME_WITHOUT_EXTENSION="Appdome_secured_app" 
        elif [[ "$OUTPUT_APP_NAME" == */* ]]; then
          OUTPUT_PATH="$(dirname "$OUTPUT_APP_NAME")/"
          OUTPUT_APP_NAME_WITHOUT_EXTENSION=$(basename -- "$OUTPUT_APP_NAME" | cut -d. -f1)
        else
          OUTPUT_PATH="./output/"
          OUTPUT_APP_NAME_WITHOUT_EXTENSION=$(basename -- "$OUTPUT_APP_NAME" | cut -d. -f1)
        fi
        echo "OUTPUT_DIR=$OUTPUT_PATH" >> $GITHUB_OUTPUT
        echo "OUTPUT_APP_NAME_WITHOUT_EXTENSION=$OUTPUT_APP_NAME_WITHOUT_EXTENSION" >> $GITHUB_OUTPUT
      shell: bash
      env:
        INPUTS_OUTPUT_APP_NAME: ${{ inputs.OUTPUT_APP_NAME }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.job }}_${{ github.run_number }}_Appdome_Outputs
        path: ${{ steps.get-output-dir.outputs.OUTPUT_DIR }}
    - name: List files in output directory
      run: ls -al "${{ steps.get-output-dir.outputs.OUTPUT_DIR }}"
      shell: bash
    - name: Find secure app file
      id: secure_app_file
      run: |
         FILE=$(find "${{ steps.get-output-dir.outputs.OUTPUT_DIR }}" -type f -name "${{ steps.get-output-dir.outputs.OUTPUT_APP_NAME_WITHOUT_EXTENSION }}.*" )
         echo "APPDOME_SECURED_APP=$FILE" >> $GITHUB_ENV
         FILE_SECOND_OUTPUT=$(find "${{ steps.get-output-dir.outputs.OUTPUT_DIR }}" -type f -name "${{ steps.get-output-dir.outputs.OUTPUT_APP_NAME_WITHOUT_EXTENSION }}_second_output.apk" )
         if [ -e "$FILE_SECOND_OUTPUT" ]; then
            echo "APPDOME_SECURED_APP_SECOND_OUTPUT=$FILE_SECOND_OUTPUT" >> $GITHUB_ENV
         fi
      shell: bash
